

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: go
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
    environment:
      - CASSANDRA_HOST=cassandra
      - DATABASE_URL= postgres://postgres:1234@db:5432/go
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      cassandra:
        condition: service_healthy
      minio:
        condition: service_healthy


  nginx:
    image: nginx:latest
    build:
      context: ./frontend
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/html:/usr/share/nginx/html

    ports:
      - "80:80"

    minio:
      image: minio/minio
      ports:
        - "9000:9000" 
        - "9001:9001" 
      environment:
        MINIO_ACCESS_KEY: 123123123
        
        MINIO_SECRET_KEY: 123123123
      volumes:
        - minio_data:/data
      healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
        interval: 10s
        timeout: 5s
        retries: 5

    command: server /data --console-address ":9001" 
  cassandra:
    image: cassandra:latest
    container_name: cassandra
    ports:
      - "9042:9042"
    volumes:
      - cassandra-data:/var/lib/cassandra
    healthcheck:
      test: ["CMD", "cqlsh", "-e", "SELECT now() FROM system.local"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db_data:
  minio_data:
  cassandra-data:

